owkin/GrAIdient

CHANGELOG.md
Sources/GrAIdient/LayerSeq/SumSeq.swift
Sources/GrAIdient/Utils/Serialization.swift
Tests/GrAITests/LayerSeqDirtyTests.swift
Tests/GrAITests/LayerSeqTests.swift

**Changes**: 
- added SumSeq
- added LayerSeqDirtyFlowTests

✨ feat(layer_seq): SumSeq

---

CHANGELOG.md
Sources/GrAIdient/Layer1D/Concat1D.swift
Sources/GrAIdient/Layer1D/DotProduct1D.swift
Sources/GrAIdient/LayerSeq/ConcatSeq.swift
Sources/GrAIdient/Metal/Kernel/LayerSeq.metal
Sources/GrAIdient/Metal/MetalKernel.swift
Sources/GrAIdient/Utils/Serialization.swift
Tests/GrAITests/LayerSeqTests.swift

**Changes**: 
- added Concat1Seq & Concat2Seq

✨ feat(layer_seq): Concat1Seq & Concat2Seq

---

CHANGELOG.md
Sources/GrAIdient/LayerSeq/ConstantSeq.swift
Sources/GrAIdient/Metal/Kernel/LayerSeq.metal
Sources/GrAIdient/Metal/MetalKernel.swift
Sources/GrAIdient/Utils/Serialization.swift
Tests/GrAITests/LayerSeqDirtyTests.swift
Tests/GrAITests/LayerSeqTests.swift

**Changes**: 
- Constant2Seq & Constant12Seq

✨ feat(layer_seq): Constant12Seq  & Constant2Seq

---

CHANGELOG.md
Sources/GrAIdient/Core/Layer/LayerNormalization.swift
Sources/GrAIdient/LayerSeq/LayerNormSeq.swift
Sources/GrAIdient/Metal/Kernel/BatchNorm.metal
Sources/GrAIdient/Metal/Kernel/InstanceNorm.metal
Sources/GrAIdient/Metal/Kernel/LayerNorm.metal
Sources/GrAIdient/Metal/MetalKernel.swift
Sources/GrAIdient/Utils/Serialization.swift
Tests/GrAITests/LayerSeqDirtyTests.swift
Tests/GrAITests/LayerSeqTests.swift

**Changes**: 
- added LayerNormSeq & LayerNormalization

✨ feat(layer_seq): LayerNormSeq & LayerNormalization

---

CHANGELOG.md
Sources/GrAIdient/LayerSeq/QuerySeq.swift
Sources/GrAIdient/Metal/Kernel/LayerSeq.metal
Sources/GrAIdient/Metal/MetalKernel.swift
Sources/GrAIdient/Utils/Serialization.swift
Tests/GrAITests/LayerSeqDirtyTests.swift
Tests/GrAITests/LayerSeqTests.swift

**Changes**: 
- added QuerySeq

✨ feat(layer_seq): QuerySeq

---

CHANGELOG.md
Sources/GrAIdient/Layer1D/Softmax1D.swift
Sources/GrAIdient/LayerSeq/ActivationSeq.swift
Sources/GrAIdient/LayerSeq/ConstantSeq.swift
Sources/GrAIdient/LayerSeq/SoftmaxSeq.swift
Sources/GrAIdient/Metal/Kernel/LayerSeq.metal
Sources/GrAIdient/Metal/MetalKernel.swift
Sources/GrAIdient/Utils/Serialization.swift
Tests/GrAITests/LayerSeqDirtyTests.swift
Tests/GrAITests/LayerSeqTests.swift

**Changes**:
- added SoftmaxSeq

✨ feat(layer_seq): SoftmaxSeq

---

CHANGELOG.md
Sources/GrAIdient/LayerSeq/ValueSeq.swift
Sources/GrAIdient/Metal/Kernel/LayerSeq.metal
Sources/GrAIdient/Metal/MetalKernel.swift
Sources/GrAIdient/Utils/Serialization.swift
Tests/GrAITests/LayerSeqDirtyTests.swift
Tests/GrAITests/LayerSeqTests.swift

**Changes**: 
- added ValueSeq

✨ feat(layer_seq): ValueSeq

---

CHANGELOG.md
Sources/GrAIdient/Core/Function/Normalization.swift
Sources/GrAIdient/Core/Layer/LayerNormalization.swift
Sources/GrAIdient/LayerSeq/LayerNormSeq.swift
Sources/GrAIdient/Metal/Kernel/BatchNorm.metal
Sources/GrAIdient/Metal/Kernel/InstanceNorm.metal
Sources/GrAIdient/Metal/Kernel/LayerNorm.metal
Sources/GrAIdient/Metal/MetalKernel.swift
Tests/GrAITorchTests/Base/Model.swift
Tests/GrAITorchTests/Base/Utils.swift
Tests/GrAITorchTests/Base/python_lib/__init__.py
Tests/GrAITorchTests/Base/python_lib/gradient.py
Tests/GrAITorchTests/Base/python_lib/model.py
Tests/GrAITorchTests/Base/python_lib/weight.py
Tests/GrAITorchTests/GrAITorchTests.swift

**Changes**: 
- align LayerNormSeq on PyTorch counterpart
- integration test

🚨 test(integration): update & validate LayerNormSeq

---

CHANGELOG.md
Sources/GrAIdient/LayerSeq/ValueSeq.swift
Sources/GrAIdient/Metal/Kernel/LayerSeq.metal
Tests/GrAITorchTests/Base/python_lib/model.py

**Changes**: 
- update ValueSeq operation

🐛 fix: update ValueSeq operation

---

CHANGELOG.md
Sources/GrAIdient/Core/Function/Activation.swift
Sources/GrAIdient/Metal/Kernel/Activation.metal
Sources/GrAIdient/Metal/MetalKernel.swift
Tests/GrAITests/Activation1DTests.swift
Tests/GrAITests/Activation2DTests.swift
Tests/GrAITests/ActivationSeqTests.swift

**Changes**: 
- GELU activation function (approximation)

✨ feat(core): GELU activation function

---

AUTHORS
CHANGELOG.md
Sources/GrAIdient/Core/Function/Activation.swift
Sources/GrAIdient/Layer2D/Convolution2D.swift
Tests/GrAIExamples/TransformerExample.swift

**Changes**: 
- added VisionTransformer example
- removed redundant line in Convolution2D

✨ feat(examples): adding Transformer training example

---

CHANGELOG.md
Sources/GrAIdient/Layer2D/VQ2D.swift
Sources/GrAIdient/Metal/Kernel/VQ2D.metal
Sources/GrAIdient/Metal/MetalKernel.swift
Sources/GrAIdient/Utils/Serialization.swift
Tests/GrAITests/Layer2DDirtyTests.swift
Tests/GrAITests/Layer2DTests.swift

✨ feat(layer_2d): VQ2D

---

CHANGELOG.md
Sources/GrAIdient/Layer2D/Transform/ResizeBilinear.swift
Sources/GrAIdient/Utils/Serialization.swift
Tests/GrAITests/Layer2DTests.swift
Tests/GrAITorchTests/Base/Model.swift
Tests/GrAITorchTests/Base/python_lib/model.py
Tests/GrAITorchTests/GrAITorchTests.swift

**Changes**: 
- add ResizeBilinear layer
- integration tests for ResizeBilinear

🚨 test(integration): resize alignment with PyTorch

---

CHANGELOG.md
Sources/GrAIdient/Layer2D/Normalize2D.swift
Sources/GrAIdient/Metal/Kernel/Layer2D.metal
Sources/GrAIdient/Metal/MetalKernel.swift
Sources/GrAIdient/Utils/Serialization.swift
Tests/GrAITests/Layer2DDirtyTests.swift
Tests/GrAITests/Layer2DTests.swift
Tests/GrAITorchTests/Base/Model.swift
Tests/GrAITorchTests/Base/python_lib/model.py

**Changes**:
- Normalize12D, Normalize122D
- unit & integration tests

✨ feat(layer_2d): Normalize2D

---

CHANGELOG.md
Sources/GrAIdient/Layer1D/Base/LayerInput1D.swift
Sources/GrAIdient/Layer1D/Base/LayerOutput1D.swift
Sources/GrAIdient/Layer1D/Input1D.swift
Sources/GrAIdient/Layer1D/LinearError1D.swift
Sources/GrAIdient/Layer1D/MSE1D.swift
Sources/GrAIdient/Layer2D/Base/LayerInput2D.swift
Sources/GrAIdient/Layer2D/Base/LayerOutput2D.swift
Sources/GrAIdient/Layer2D/Input2D.swift
Sources/GrAIdient/Layer2D/MSE2D.swift
Sources/GrAIdient/Layer2D/SimilarityBatchError2D.swift
Sources/GrAIdient/Metal/Kernel/Layer2D.metal
Sources/GrAIdient/Metal/MetalKernel.swift
Sources/GrAIdient/Utils/Serialization.swift
Tests/GrAITests/Base/Input2DSimilarityBatchError2DCase.swift
Tests/GrAITests/Layer2DTests.swift
Tests/GrAITorchTests/Base/Model.swift
Tests/GrAITorchTests/Base/Utils.swift
Tests/GrAITorchTests/Base/python_lib/__init__.py
Tests/GrAITorchTests/Base/python_lib/gradient.py
Tests/GrAITorchTests/Base/python_lib/model.py
Tests/GrAITorchTests/GrAITorchTests.swift

**Changes**:
- SimilarityBatchError2D
- unit & integration tests

✨ feat(layer_2d): SimilarityBatchError2D

---

CHANGELOG.md
Sources/GrAIdient/Layer2D/Transform/ResizeBilinearCrop.swift
Sources/GrAIdient/Layer2D/Transform/ResizeBilinearPad.swift
Sources/GrAIdient/Layer2D/Transform/Rotate2D.swift
Sources/GrAIdient/Metal/Kernel/Layer2D.metal
Tests/GrAITests/Layer2DDirtyTests.swift
Tests/GrAITests/Layer2DTests.swift

**Changes**: 
- API for random transforms for resize and rotate

🔨 refactor(layer_2d): API for random transforms

---

CHANGELOG.md
Sources/GrAIdient/Layer2D/VQ2D.swift
Sources/GrAIdient/Metal/Kernel/VQ2D.metal
Tests/GrAITests/Layer2DDirtyTests.swift
Tests/GrAITests/Layer2DTests.swift

**Changes**: 
- remove computeVQ API from VQ2D

🔨 refactor(layer_2d): remove computeVQ

---

CHANGELOG.md
Sources/GrAITestsUtils/Trainer.swift
Tests/GrAITests/Layer1DTests.swift
Tests/GrAITests/Layer2DTests.swift
Tests/GrAITests/LayerSeqTests.swift

**Changes**: 
- FlowAccumulateTrainer tests

🚨 test: FlowAccumulateTrainer

---

CHANGELOG.md
Sources/GrAIdient/Layer2D/VQ2D.swift

**Changes**: 
- expose indices in VQ2D

🔨 refactor(layer_2d): expose indices in VQ2D

---

CHANGELOG.md
Sources/GrAIdient/LayerSeq/VQSeq.swift
Sources/GrAIdient/Metal/Kernel/VQ2D.metal
Sources/GrAIdient/Metal/Kernel/VQSeq.metal
Sources/GrAIdient/Metal/MetalConfig.swift
Sources/GrAIdient/Utils/Serialization.swift
Tests/GrAITests/LayerSeqDirtyTests.swift
Tests/GrAITests/LayerSeqTests.swift

✨ feat(layer_seq): VQSeq

---

CHANGELOG.md

**Changes**: 
- update changelog

🔧 chore: release 0.3.0

---

CHANGELOG.md
Sources/GrAIdient/Layer1D/Dropout1D.swift
Sources/GrAIdient/Metal/Kernel/Layer1D.metal
Sources/GrAIdient/Metal/MetalConfig.swift
Sources/GrAIdient/Utils/Serialization.swift
Tests/GrAITests/Layer1DDirtyTests.swift
Tests/GrAITests/Layer1DTests.swift

✨ feat: Dropout1D

---

CHANGELOG.md
Sources/GrAIdient/Core/Layer/Layer.swift
Sources/GrAIdient/Core/Model/Model.swift
Sources/GrAIdient/Layer1D/Base/Layer1D.swift
Sources/GrAIdient/Layer2D/Base/Layer2D.swift
Sources/GrAIdient/Layer2D/Convolution2D.swift
Sources/GrAIdient/Layer2D/Normalize2D.swift
Sources/GrAIdient/LayerSeq/Base/LayerSeq.swift

**Changes**: 
- add model API to initForward and initBackward

✨ feat(core): initForward,Backward model API

---

CHANGELOG.md
Sources/GrAIdient/Metal/MetalKernel.swift
Sources/GrAIdient/Utils/Image.swift
Tests/GrAIExamples/Base/Utils.swift
Tests/GrAITorchTests/Base/Utils.swift

**Changes**: 
- use cgImage instead of tiffRepresentation to convert NSImage
- refer to miniconda rather than anaconda
- update setBytes implementation

🐛 fix: run on Apple Silicon

---

CHANGELOG.md
Sources/GrAIdient/Layer2D/LayerCAM2D.swift
Sources/GrAIdient/Layer2D/VQ2D.swift
Sources/GrAIdient/LayerSeq/Base/LayerSeq.swift
Sources/GrAIdient/LayerSeq/LayerCAMSeq.swift
Sources/GrAIdient/LayerSeq/VQSeq.swift
Sources/GrAIdient/Metal/Kernel/Layer2D.metal
Sources/GrAIdient/Metal/Kernel/LayerSeq.metal
Sources/GrAIdient/Metal/Kernel/VQ2D.metal
Sources/GrAIdient/Metal/Kernel/VQSeq.metal
Sources/GrAIdient/Metal/MetalConfig.swift
Sources/GrAIdient/Utils/Serialization.swift
Tests/GrAITests/Layer2DTests.swift
Tests/GrAITests/LayerSeqTests.swift

**Changes**: 
- added LayerCAM2D and updated VQGrad2D to use it
- added LayerCAMSeq and updated VQGradSeq to us it

✨ feat: LayerCAM2D -> VQGrad2D, LayerCAMSeq -> VQGradSeq

---

CHANGELOG.md
Sources/GrAIdient/Core/Layer/LayerUpdate.swift
Sources/GrAIdient/Layer1D/Constant1D.swift
Sources/GrAIdient/Layer1D/FullyConnected.swift
Sources/GrAIdient/Layer2D/Constant2D.swift
Sources/GrAIdient/Layer2D/Convolution2D.swift
Sources/GrAIdient/Layer2D/VQ2D.swift
Sources/GrAIdient/LayerSeq/ConstantSeq.swift
Sources/GrAIdient/LayerSeq/FullyConnectedPatch.swift
Sources/GrAIdient/LayerSeq/FullyConnectedSeq.swift
Sources/GrAIdient/LayerSeq/VQSeq.swift
Sources/GrAIdient/Utils/Buffer.swift
Tests/GrAIExamples/Base/Model.swift
Tests/GrAIExamples/Base/Utils.swift
Tests/GrAIExamples/Base/python_lib/llm/generate.py
Tests/GrAIExamples/Base/python_lib/llm/model.py
Tests/GrAIExamples/Base/python_lib/llm/tokenizer.py
Tests/GrAIExamples/Base/python_lib/weight.py
Tests/GrAIExamples/Base/setup.py
Tests/GrAITorchTests/Base/Utils.swift
Tests/GrAITorchTests/Base/setup.py

**Changes:**
- copy & generate weights faster on GPU
- init LLM example

🚀 perf: copy & generate weights faster

---

CHANGELOG.md
Sources/GrAIdient/Core/Function/Normalization.swift
Sources/GrAIdient/Core/Layer/LayerNormalization.swift
Sources/GrAIdient/LayerSeq/RMSNormSeq.swift
Sources/GrAIdient/Metal/Kernel/EmbeddingSeqFloat.metal
Sources/GrAIdient/Metal/Kernel/EmbeddingSeqHalf.metal
Sources/GrAIdient/Metal/Kernel/FullyConnectedSeqFloat.metal
Sources/GrAIdient/Metal/Kernel/FullyConnectedSeqHalf.metal
Sources/GrAIdient/Metal/Kernel/RMSNormSeqFloat.metal
Sources/GrAIdient/Metal/Kernel/RMSNormSeqHalf.metal
Sources/GrAIdient/Metal/MetalConfig.swift
Sources/GrAIdient/Utils/Serialization.swift
Tests/GrAIExamples/Base/python_lib/nlp/model.py
Tests/GrAIExamples/NLPExample.swift
Tests/GrAITests/Activation2DTests.swift
Tests/GrAITests/ActivationSeqTests.swift
Tests/GrAITests/Layer2DTests.swift
Tests/GrAITests/LayerSeqTests.swift
Tests/GrAITests/NLPTests.swift

**Changes:**
- RMSNormSeq
- small optimisations for EmbeddingSeq and FullyConnectedSeq

✨ feat(layer_seq): RMSNormSeq

---

.github/workflows/unit-tests.yml
CHANGELOG.md
Sources/GrAIdient/LayerSeq/RoPESeq.swift
Sources/GrAIdient/LayerSeq/SoftmaxSeq.swift
Sources/GrAIdient/Metal/Kernel/LayerSeqFloat.metal
Sources/GrAIdient/Metal/Kernel/LayerSeqHalf.metal
Sources/GrAIdient/Metal/MetalConfig.swift
Sources/GrAIdient/Utils/Serialization.swift
Tests/GrAIExamples/Base/python_lib/nlp/generate.py
Tests/GrAIExamples/Base/python_lib/nlp/model.py
Tests/GrAIExamples/NLPExample.swift
Tests/GrAITests/Activation1DTests.swift
Tests/GrAITests/Activation2DTests.swift
Tests/GrAITests/Layer2DTests.swift
Tests/GrAITests/LayerSeqTests.swift
Tests/GrAITests/NLPTests.swift

✨ feat(layer_seq): RoPESeq

---

CHANGELOG.md
Sources/GrAIdient/LayerSeq/QuerySeq.swift
Sources/GrAIdient/LayerSeq/SoftmaxSeq.swift
Sources/GrAIdient/LayerSeq/ValueSeq.swift
Sources/GrAIdient/Metal/Kernel/NLPFloat.metal
Sources/GrAIdient/Metal/Kernel/NLPHalf.metal
Tests/GrAIExamples/LLMExample.swift
Tests/GrAITests/NLPTests.swift

**Changes:**
- LLM sliding window
- add tests with batch size
- fix context length for valueCausal

✨ feat(layer_seq): LLM sliding window

---

CHANGELOG.md
Docs/Examples/LLM.md
Sources/GrAIdient/Core/Function/Normalization.swift
Sources/GrAIdient/Core/Layer/LayerNormalization.swift
Sources/GrAIdient/Core/Model/Model.swift
Sources/GrAIdient/LayerSeq/RMSNormSeq.swift
Sources/GrAIdient/Metal/Kernel/RMSNormSeqFloat.metal
Sources/GrAIdient/Metal/Kernel/RMSNormSeqHalf.metal
Tests/GrAIExamples/Base/python_lib/__init__.py
Tests/GrAIExamples/Base/python_lib/nlp/gemma2/generate.py
Tests/GrAIExamples/Base/python_lib/nlp/gemma2/model.py
Tests/GrAIExamples/Base/python_lib/nlp/gemma2/tokenizer.py
Tests/GrAIExamples/Base/python_lib/nlp/generate.py
Tests/GrAIExamples/Base/python_lib/weight.py
Tests/GrAIExamples/LLMExample.swift
Tests/GrAIExamples/LLMExampleTests.swift
Tests/GrAITests/NLPTests.swift

**Changes:**
- integrate Gemma-2-2B
- addUnitOffset in RMSNorm

🚀 test(examples): integrate Gemma2-2B

---

CHANGELOG.md
Docs/Contributing/CONTRIBUTING.md

**Changes:**
- update changelog for release 0.4.0

🔧 chore: update changelog
